In [118]:
# import required libraries
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import array_to_img
import math

In [306]:
path='chinese mnist/data/data/input_'

arrays = [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]

for person in range(1, 101):
    for i in range(1,11):
        for j in range(1,16):
            img = load_img(path + str(person) + '_' + str(i) + '_' + str(j) + '.jpg')
            
            # convert to numpy array
            img_array = img_to_array(img)
            bw_array = np.empty(1)
                
            for x in range(len(img_array)):
                for y in range(len(img_array)):
                    if i == 0 and j == 0:
                        bw_array = np.array(img_array[x][y][0])
                    else:
                        bw_array = np.append(bw_array, img_array[x][y][0])       
            arrays[j-1].append(bw_array)
            
            print(str(person) + '_' + str(i) + '_' + str(j))

print(arrays[0])

np.save('zeros', arrays[0])
np.save('ones', arrays[1])
np.save('twos', arrays[2])
np.save('threes',arrays[3])
np.save('fours',arrays[4])
np.save('fives',arrays[5])
np.save('sixes',arrays[6])
np.save('sevens', arrays[7])
np.save('eights', arrays[8])
np.save('nines',arrays[9])
np.save('tens', arrays[10])
np.save('hundreds',arrays[11])
np.save('thousands',arrays[12])
np.save('tenthous',arrays[13])
np.save('tenmils',arrays[14])


1_1_1
1_1_2
1_1_3
1_1_4
1_1_5
1_1_6
1_1_7
1_1_8
1_1_9
1_1_10
1_1_11
1_1_12
1_1_13
1_1_14
1_1_15
1_2_1
1_2_2
1_2_3
1_2_4
1_2_5
1_2_6
1_2_7
1_2_8
1_2_9
1_2_10
1_2_11
1_2_12
1_2_13
1_2_14
1_2_15
1_3_1
1_3_2
1_3_3
1_3_4
1_3_5
1_3_6
1_3_7
1_3_8
1_3_9
1_3_10
1_3_11
1_3_12
1_3_13
1_3_14
1_3_15
1_4_1
1_4_2
1_4_3
1_4_4
1_4_5
1_4_6
1_4_7
1_4_8
1_4_9
1_4_10
1_4_11
1_4_12
1_4_13
1_4_14
1_4_15
1_5_1
1_5_2
1_5_3
1_5_4
1_5_5
1_5_6
1_5_7
1_5_8
1_5_9
1_5_10
1_5_11
1_5_12
1_5_13
1_5_14
1_5_15
1_6_1
1_6_2
1_6_3
1_6_4
1_6_5
1_6_6
1_6_7
1_6_8
1_6_9
1_6_10
1_6_11
1_6_12
1_6_13
1_6_14
1_6_15
1_7_1
1_7_2
1_7_3
1_7_4
1_7_5
1_7_6
1_7_7
1_7_8
1_7_9
1_7_10
1_7_11
1_7_12
1_7_13
1_7_14
1_7_15
1_8_1
1_8_2
1_8_3
1_8_4
1_8_5
1_8_6
1_8_7
1_8_8
1_8_9
1_8_10
1_8_11
1_8_12
1_8_13
1_8_14
1_8_15
1_9_1
1_9_2
1_9_3
1_9_4
1_9_5
1_9_6
1_9_7
1_9_8
1_9_9
1_9_10
1_9_11
1_9_12
1_9_13
1_9_14
1_9_15
1_10_1
1_10_2
1_10_3
1_10_4
1_10_5
1_10_6
1_10_7
1_10_8
1_10_9
1_10_10
1_10_11
1_10_12
1_10_13
1_10_14
1_10_15
2_1_1
2_1_2
2_1_3
2_1_4
2

9_5_4
9_5_5
9_5_6
9_5_7
9_5_8
9_5_9
9_5_10
9_5_11
9_5_12
9_5_13
9_5_14
9_5_15
9_6_1
9_6_2
9_6_3
9_6_4
9_6_5
9_6_6
9_6_7
9_6_8
9_6_9
9_6_10
9_6_11
9_6_12
9_6_13
9_6_14
9_6_15
9_7_1
9_7_2
9_7_3
9_7_4
9_7_5
9_7_6
9_7_7
9_7_8
9_7_9
9_7_10
9_7_11
9_7_12
9_7_13
9_7_14
9_7_15
9_8_1
9_8_2
9_8_3
9_8_4
9_8_5
9_8_6
9_8_7
9_8_8
9_8_9
9_8_10
9_8_11
9_8_12
9_8_13
9_8_14
9_8_15
9_9_1
9_9_2
9_9_3
9_9_4
9_9_5
9_9_6
9_9_7
9_9_8
9_9_9
9_9_10
9_9_11
9_9_12
9_9_13
9_9_14
9_9_15
9_10_1
9_10_2
9_10_3
9_10_4
9_10_5
9_10_6
9_10_7
9_10_8
9_10_9
9_10_10
9_10_11
9_10_12
9_10_13
9_10_14
9_10_15
10_1_1
10_1_2
10_1_3
10_1_4
10_1_5
10_1_6
10_1_7
10_1_8
10_1_9
10_1_10
10_1_11
10_1_12
10_1_13
10_1_14
10_1_15
10_2_1
10_2_2
10_2_3
10_2_4
10_2_5
10_2_6
10_2_7
10_2_8
10_2_9
10_2_10
10_2_11
10_2_12
10_2_13
10_2_14
10_2_15
10_3_1
10_3_2
10_3_3
10_3_4
10_3_5
10_3_6
10_3_7
10_3_8
10_3_9
10_3_10
10_3_11
10_3_12
10_3_13
10_3_14
10_3_15
10_4_1
10_4_2
10_4_3
10_4_4
10_4_5
10_4_6
10_4_7
10_4_8
10_4_9
10_4_10
10_4_11
10_4_12
10_4_13

16_8_15
16_9_1
16_9_2
16_9_3
16_9_4
16_9_5
16_9_6
16_9_7
16_9_8
16_9_9
16_9_10
16_9_11
16_9_12
16_9_13
16_9_14
16_9_15
16_10_1
16_10_2
16_10_3
16_10_4
16_10_5
16_10_6
16_10_7
16_10_8
16_10_9
16_10_10
16_10_11
16_10_12
16_10_13
16_10_14
16_10_15
17_1_1
17_1_2
17_1_3
17_1_4
17_1_5
17_1_6
17_1_7
17_1_8
17_1_9
17_1_10
17_1_11
17_1_12
17_1_13
17_1_14
17_1_15
17_2_1
17_2_2
17_2_3
17_2_4
17_2_5
17_2_6
17_2_7
17_2_8
17_2_9
17_2_10
17_2_11
17_2_12
17_2_13
17_2_14
17_2_15
17_3_1
17_3_2
17_3_3
17_3_4
17_3_5
17_3_6
17_3_7
17_3_8
17_3_9
17_3_10
17_3_11
17_3_12
17_3_13
17_3_14
17_3_15
17_4_1
17_4_2
17_4_3
17_4_4
17_4_5
17_4_6
17_4_7
17_4_8
17_4_9
17_4_10
17_4_11
17_4_12
17_4_13
17_4_14
17_4_15
17_5_1
17_5_2
17_5_3
17_5_4
17_5_5
17_5_6
17_5_7
17_5_8
17_5_9
17_5_10
17_5_11
17_5_12
17_5_13
17_5_14
17_5_15
17_6_1
17_6_2
17_6_3
17_6_4
17_6_5
17_6_6
17_6_7
17_6_8
17_6_9
17_6_10
17_6_11
17_6_12
17_6_13
17_6_14
17_6_15
17_7_1
17_7_2
17_7_3
17_7_4
17_7_5
17_7_6
17_7_7
17_7_8
17_7_9
17_7_10
17_7_11
17_7_12
17

24_1_12
24_1_13
24_1_14
24_1_15
24_2_1
24_2_2
24_2_3
24_2_4
24_2_5
24_2_6
24_2_7
24_2_8
24_2_9
24_2_10
24_2_11
24_2_12
24_2_13
24_2_14
24_2_15
24_3_1
24_3_2
24_3_3
24_3_4
24_3_5
24_3_6
24_3_7
24_3_8
24_3_9
24_3_10
24_3_11
24_3_12
24_3_13
24_3_14
24_3_15
24_4_1
24_4_2
24_4_3
24_4_4
24_4_5
24_4_6
24_4_7
24_4_8
24_4_9
24_4_10
24_4_11
24_4_12
24_4_13
24_4_14
24_4_15
24_5_1
24_5_2
24_5_3
24_5_4
24_5_5
24_5_6
24_5_7
24_5_8
24_5_9
24_5_10
24_5_11
24_5_12
24_5_13
24_5_14
24_5_15
24_6_1
24_6_2
24_6_3
24_6_4
24_6_5
24_6_6
24_6_7
24_6_8
24_6_9
24_6_10
24_6_11
24_6_12
24_6_13
24_6_14
24_6_15
24_7_1
24_7_2
24_7_3
24_7_4
24_7_5
24_7_6
24_7_7
24_7_8
24_7_9
24_7_10
24_7_11
24_7_12
24_7_13
24_7_14
24_7_15
24_8_1
24_8_2
24_8_3
24_8_4
24_8_5
24_8_6
24_8_7
24_8_8
24_8_9
24_8_10
24_8_11
24_8_12
24_8_13
24_8_14
24_8_15
24_9_1
24_9_2
24_9_3
24_9_4
24_9_5
24_9_6
24_9_7
24_9_8
24_9_9
24_9_10
24_9_11
24_9_12
24_9_13
24_9_14
24_9_15
24_10_1
24_10_2
24_10_3
24_10_4
24_10_5
24_10_6
24_10_7
24_10_8
24_10_9
24_10_10

31_4_11
31_4_12
31_4_13
31_4_14
31_4_15
31_5_1
31_5_2
31_5_3
31_5_4
31_5_5
31_5_6
31_5_7
31_5_8
31_5_9
31_5_10
31_5_11
31_5_12
31_5_13
31_5_14
31_5_15
31_6_1
31_6_2
31_6_3
31_6_4
31_6_5
31_6_6
31_6_7
31_6_8
31_6_9
31_6_10
31_6_11
31_6_12
31_6_13
31_6_14
31_6_15
31_7_1
31_7_2
31_7_3
31_7_4
31_7_5
31_7_6
31_7_7
31_7_8
31_7_9
31_7_10
31_7_11
31_7_12
31_7_13
31_7_14
31_7_15
31_8_1
31_8_2
31_8_3
31_8_4
31_8_5
31_8_6
31_8_7
31_8_8
31_8_9
31_8_10
31_8_11
31_8_12
31_8_13
31_8_14
31_8_15
31_9_1
31_9_2
31_9_3
31_9_4
31_9_5
31_9_6
31_9_7
31_9_8
31_9_9
31_9_10
31_9_11
31_9_12
31_9_13
31_9_14
31_9_15
31_10_1
31_10_2
31_10_3
31_10_4
31_10_5
31_10_6
31_10_7
31_10_8
31_10_9
31_10_10
31_10_11
31_10_12
31_10_13
31_10_14
31_10_15
32_1_1
32_1_2
32_1_3
32_1_4
32_1_5
32_1_6
32_1_7
32_1_8
32_1_9
32_1_10
32_1_11
32_1_12
32_1_13
32_1_14
32_1_15
32_2_1
32_2_2
32_2_3
32_2_4
32_2_5
32_2_6
32_2_7
32_2_8
32_2_9
32_2_10
32_2_11
32_2_12
32_2_13
32_2_14
32_2_15
32_3_1
32_3_2
32_3_3
32_3_4
32_3_5
32_3_6
32_3_7
32_3_8
3

38_7_10
38_7_11
38_7_12
38_7_13
38_7_14
38_7_15
38_8_1
38_8_2
38_8_3
38_8_4
38_8_5
38_8_6
38_8_7
38_8_8
38_8_9
38_8_10
38_8_11
38_8_12
38_8_13
38_8_14
38_8_15
38_9_1
38_9_2
38_9_3
38_9_4
38_9_5
38_9_6
38_9_7
38_9_8
38_9_9
38_9_10
38_9_11
38_9_12
38_9_13
38_9_14
38_9_15
38_10_1
38_10_2
38_10_3
38_10_4
38_10_5
38_10_6
38_10_7
38_10_8
38_10_9
38_10_10
38_10_11
38_10_12
38_10_13
38_10_14
38_10_15
39_1_1
39_1_2
39_1_3
39_1_4
39_1_5
39_1_6
39_1_7
39_1_8
39_1_9
39_1_10
39_1_11
39_1_12
39_1_13
39_1_14
39_1_15
39_2_1
39_2_2
39_2_3
39_2_4
39_2_5
39_2_6
39_2_7
39_2_8
39_2_9
39_2_10
39_2_11
39_2_12
39_2_13
39_2_14
39_2_15
39_3_1
39_3_2
39_3_3
39_3_4
39_3_5
39_3_6
39_3_7
39_3_8
39_3_9
39_3_10
39_3_11
39_3_12
39_3_13
39_3_14
39_3_15
39_4_1
39_4_2
39_4_3
39_4_4
39_4_5
39_4_6
39_4_7
39_4_8
39_4_9
39_4_10
39_4_11
39_4_12
39_4_13
39_4_14
39_4_15
39_5_1
39_5_2
39_5_3
39_5_4
39_5_5
39_5_6
39_5_7
39_5_8
39_5_9
39_5_10
39_5_11
39_5_12
39_5_13
39_5_14
39_5_15
39_6_1
39_6_2
39_6_3
39_6_4
39_6_5
39_6_6
39_6_7


45_10_7
45_10_8
45_10_9
45_10_10
45_10_11
45_10_12
45_10_13
45_10_14
45_10_15
46_1_1
46_1_2
46_1_3
46_1_4
46_1_5
46_1_6
46_1_7
46_1_8
46_1_9
46_1_10
46_1_11
46_1_12
46_1_13
46_1_14
46_1_15
46_2_1
46_2_2
46_2_3
46_2_4
46_2_5
46_2_6
46_2_7
46_2_8
46_2_9
46_2_10
46_2_11
46_2_12
46_2_13
46_2_14
46_2_15
46_3_1
46_3_2
46_3_3
46_3_4
46_3_5
46_3_6
46_3_7
46_3_8
46_3_9
46_3_10
46_3_11
46_3_12
46_3_13
46_3_14
46_3_15
46_4_1
46_4_2
46_4_3
46_4_4
46_4_5
46_4_6
46_4_7
46_4_8
46_4_9
46_4_10
46_4_11
46_4_12
46_4_13
46_4_14
46_4_15
46_5_1
46_5_2
46_5_3
46_5_4
46_5_5
46_5_6
46_5_7
46_5_8
46_5_9
46_5_10
46_5_11
46_5_12
46_5_13
46_5_14
46_5_15
46_6_1
46_6_2
46_6_3
46_6_4
46_6_5
46_6_6
46_6_7
46_6_8
46_6_9
46_6_10
46_6_11
46_6_12
46_6_13
46_6_14
46_6_15
46_7_1
46_7_2
46_7_3
46_7_4
46_7_5
46_7_6
46_7_7
46_7_8
46_7_9
46_7_10
46_7_11
46_7_12
46_7_13
46_7_14
46_7_15
46_8_1
46_8_2
46_8_3
46_8_4
46_8_5
46_8_6
46_8_7
46_8_8
46_8_9
46_8_10
46_8_11
46_8_12
46_8_13
46_8_14
46_8_15
46_9_1
46_9_2
46_9_3
46_9_4
46_9_5

53_3_4
53_3_5
53_3_6
53_3_7
53_3_8
53_3_9
53_3_10
53_3_11
53_3_12
53_3_13
53_3_14
53_3_15
53_4_1
53_4_2
53_4_3
53_4_4
53_4_5
53_4_6
53_4_7
53_4_8
53_4_9
53_4_10
53_4_11
53_4_12
53_4_13
53_4_14
53_4_15
53_5_1
53_5_2
53_5_3
53_5_4
53_5_5
53_5_6
53_5_7
53_5_8
53_5_9
53_5_10
53_5_11
53_5_12
53_5_13
53_5_14
53_5_15
53_6_1
53_6_2
53_6_3
53_6_4
53_6_5
53_6_6
53_6_7
53_6_8
53_6_9
53_6_10
53_6_11
53_6_12
53_6_13
53_6_14
53_6_15
53_7_1
53_7_2
53_7_3
53_7_4
53_7_5
53_7_6
53_7_7
53_7_8
53_7_9
53_7_10
53_7_11
53_7_12
53_7_13
53_7_14
53_7_15
53_8_1
53_8_2
53_8_3
53_8_4
53_8_5
53_8_6
53_8_7
53_8_8
53_8_9
53_8_10
53_8_11
53_8_12
53_8_13
53_8_14
53_8_15
53_9_1
53_9_2
53_9_3
53_9_4
53_9_5
53_9_6
53_9_7
53_9_8
53_9_9
53_9_10
53_9_11
53_9_12
53_9_13
53_9_14
53_9_15
53_10_1
53_10_2
53_10_3
53_10_4
53_10_5
53_10_6
53_10_7
53_10_8
53_10_9
53_10_10
53_10_11
53_10_12
53_10_13
53_10_14
53_10_15
54_1_1
54_1_2
54_1_3
54_1_4
54_1_5
54_1_6
54_1_7
54_1_8
54_1_9
54_1_10
54_1_11
54_1_12
54_1_13
54_1_14
54_1_15
54_2_1


60_6_2
60_6_3
60_6_4
60_6_5
60_6_6
60_6_7
60_6_8
60_6_9
60_6_10
60_6_11
60_6_12
60_6_13
60_6_14
60_6_15
60_7_1
60_7_2
60_7_3
60_7_4
60_7_5
60_7_6
60_7_7
60_7_8
60_7_9
60_7_10
60_7_11
60_7_12
60_7_13
60_7_14
60_7_15
60_8_1
60_8_2
60_8_3
60_8_4
60_8_5
60_8_6
60_8_7
60_8_8
60_8_9
60_8_10
60_8_11
60_8_12
60_8_13
60_8_14
60_8_15
60_9_1
60_9_2
60_9_3
60_9_4
60_9_5
60_9_6
60_9_7
60_9_8
60_9_9
60_9_10
60_9_11
60_9_12
60_9_13
60_9_14
60_9_15
60_10_1
60_10_2
60_10_3
60_10_4
60_10_5
60_10_6
60_10_7
60_10_8
60_10_9
60_10_10
60_10_11
60_10_12
60_10_13
60_10_14
60_10_15
61_1_1
61_1_2
61_1_3
61_1_4
61_1_5
61_1_6
61_1_7
61_1_8
61_1_9
61_1_10
61_1_11
61_1_12
61_1_13
61_1_14
61_1_15
61_2_1
61_2_2
61_2_3
61_2_4
61_2_5
61_2_6
61_2_7
61_2_8
61_2_9
61_2_10
61_2_11
61_2_12
61_2_13
61_2_14
61_2_15
61_3_1
61_3_2
61_3_3
61_3_4
61_3_5
61_3_6
61_3_7
61_3_8
61_3_9
61_3_10
61_3_11
61_3_12
61_3_13
61_3_14
61_3_15
61_4_1
61_4_2
61_4_3
61_4_4
61_4_5
61_4_6
61_4_7
61_4_8
61_4_9
61_4_10
61_4_11
61_4_12
61_4_13
61_4_14
6

67_9_1
67_9_2
67_9_3
67_9_4
67_9_5
67_9_6
67_9_7
67_9_8
67_9_9
67_9_10
67_9_11
67_9_12
67_9_13
67_9_14
67_9_15
67_10_1
67_10_2
67_10_3
67_10_4
67_10_5
67_10_6
67_10_7
67_10_8
67_10_9
67_10_10
67_10_11
67_10_12
67_10_13
67_10_14
67_10_15
68_1_1
68_1_2
68_1_3
68_1_4
68_1_5
68_1_6
68_1_7
68_1_8
68_1_9
68_1_10
68_1_11
68_1_12
68_1_13
68_1_14
68_1_15
68_2_1
68_2_2
68_2_3
68_2_4
68_2_5
68_2_6
68_2_7
68_2_8
68_2_9
68_2_10
68_2_11
68_2_12
68_2_13
68_2_14
68_2_15
68_3_1
68_3_2
68_3_3
68_3_4
68_3_5
68_3_6
68_3_7
68_3_8
68_3_9
68_3_10
68_3_11
68_3_12
68_3_13
68_3_14
68_3_15
68_4_1
68_4_2
68_4_3
68_4_4
68_4_5
68_4_6
68_4_7
68_4_8
68_4_9
68_4_10
68_4_11
68_4_12
68_4_13
68_4_14
68_4_15
68_5_1
68_5_2
68_5_3
68_5_4
68_5_5
68_5_6
68_5_7
68_5_8
68_5_9
68_5_10
68_5_11
68_5_12
68_5_13
68_5_14
68_5_15
68_6_1
68_6_2
68_6_3
68_6_4
68_6_5
68_6_6
68_6_7
68_6_8
68_6_9
68_6_10
68_6_11
68_6_12
68_6_13
68_6_14
68_6_15
68_7_1
68_7_2
68_7_3
68_7_4
68_7_5
68_7_6
68_7_7
68_7_8
68_7_9
68_7_10
68_7_11
68_7_12
68_7_13
68

75_1_13
75_1_14
75_1_15
75_2_1
75_2_2
75_2_3
75_2_4
75_2_5
75_2_6
75_2_7
75_2_8
75_2_9
75_2_10
75_2_11
75_2_12
75_2_13
75_2_14
75_2_15
75_3_1
75_3_2
75_3_3
75_3_4
75_3_5
75_3_6
75_3_7
75_3_8
75_3_9
75_3_10
75_3_11
75_3_12
75_3_13
75_3_14
75_3_15
75_4_1
75_4_2
75_4_3
75_4_4
75_4_5
75_4_6
75_4_7
75_4_8
75_4_9
75_4_10
75_4_11
75_4_12
75_4_13
75_4_14
75_4_15
75_5_1
75_5_2
75_5_3
75_5_4
75_5_5
75_5_6
75_5_7
75_5_8
75_5_9
75_5_10
75_5_11
75_5_12
75_5_13
75_5_14
75_5_15
75_6_1
75_6_2
75_6_3
75_6_4
75_6_5
75_6_6
75_6_7
75_6_8
75_6_9
75_6_10
75_6_11
75_6_12
75_6_13
75_6_14
75_6_15
75_7_1
75_7_2
75_7_3
75_7_4
75_7_5
75_7_6
75_7_7
75_7_8
75_7_9
75_7_10
75_7_11
75_7_12
75_7_13
75_7_14
75_7_15
75_8_1
75_8_2
75_8_3
75_8_4
75_8_5
75_8_6
75_8_7
75_8_8
75_8_9
75_8_10
75_8_11
75_8_12
75_8_13
75_8_14
75_8_15
75_9_1
75_9_2
75_9_3
75_9_4
75_9_5
75_9_6
75_9_7
75_9_8
75_9_9
75_9_10
75_9_11
75_9_12
75_9_13
75_9_14
75_9_15
75_10_1
75_10_2
75_10_3
75_10_4
75_10_5
75_10_6
75_10_7
75_10_8
75_10_9
75_10_10
75_10_1

82_4_12
82_4_13
82_4_14
82_4_15
82_5_1
82_5_2
82_5_3
82_5_4
82_5_5
82_5_6
82_5_7
82_5_8
82_5_9
82_5_10
82_5_11
82_5_12
82_5_13
82_5_14
82_5_15
82_6_1
82_6_2
82_6_3
82_6_4
82_6_5
82_6_6
82_6_7
82_6_8
82_6_9
82_6_10
82_6_11
82_6_12
82_6_13
82_6_14
82_6_15
82_7_1
82_7_2
82_7_3
82_7_4
82_7_5
82_7_6
82_7_7
82_7_8
82_7_9
82_7_10
82_7_11
82_7_12
82_7_13
82_7_14
82_7_15
82_8_1
82_8_2
82_8_3
82_8_4
82_8_5
82_8_6
82_8_7
82_8_8
82_8_9
82_8_10
82_8_11
82_8_12
82_8_13
82_8_14
82_8_15
82_9_1
82_9_2
82_9_3
82_9_4
82_9_5
82_9_6
82_9_7
82_9_8
82_9_9
82_9_10
82_9_11
82_9_12
82_9_13
82_9_14
82_9_15
82_10_1
82_10_2
82_10_3
82_10_4
82_10_5
82_10_6
82_10_7
82_10_8
82_10_9
82_10_10
82_10_11
82_10_12
82_10_13
82_10_14
82_10_15
83_1_1
83_1_2
83_1_3
83_1_4
83_1_5
83_1_6
83_1_7
83_1_8
83_1_9
83_1_10
83_1_11
83_1_12
83_1_13
83_1_14
83_1_15
83_2_1
83_2_2
83_2_3
83_2_4
83_2_5
83_2_6
83_2_7
83_2_8
83_2_9
83_2_10
83_2_11
83_2_12
83_2_13
83_2_14
83_2_15
83_3_1
83_3_2
83_3_3
83_3_4
83_3_5
83_3_6
83_3_7
83_3_8
83_3_9
83

89_7_11
89_7_12
89_7_13
89_7_14
89_7_15
89_8_1
89_8_2
89_8_3
89_8_4
89_8_5
89_8_6
89_8_7
89_8_8
89_8_9
89_8_10
89_8_11
89_8_12
89_8_13
89_8_14
89_8_15
89_9_1
89_9_2
89_9_3
89_9_4
89_9_5
89_9_6
89_9_7
89_9_8
89_9_9
89_9_10
89_9_11
89_9_12
89_9_13
89_9_14
89_9_15
89_10_1
89_10_2
89_10_3
89_10_4
89_10_5
89_10_6
89_10_7
89_10_8
89_10_9
89_10_10
89_10_11
89_10_12
89_10_13
89_10_14
89_10_15
90_1_1
90_1_2
90_1_3
90_1_4
90_1_5
90_1_6
90_1_7
90_1_8
90_1_9
90_1_10
90_1_11
90_1_12
90_1_13
90_1_14
90_1_15
90_2_1
90_2_2
90_2_3
90_2_4
90_2_5
90_2_6
90_2_7
90_2_8
90_2_9
90_2_10
90_2_11
90_2_12
90_2_13
90_2_14
90_2_15
90_3_1
90_3_2
90_3_3
90_3_4
90_3_5
90_3_6
90_3_7
90_3_8
90_3_9
90_3_10
90_3_11
90_3_12
90_3_13
90_3_14
90_3_15
90_4_1
90_4_2
90_4_3
90_4_4
90_4_5
90_4_6
90_4_7
90_4_8
90_4_9
90_4_10
90_4_11
90_4_12
90_4_13
90_4_14
90_4_15
90_5_1
90_5_2
90_5_3
90_5_4
90_5_5
90_5_6
90_5_7
90_5_8
90_5_9
90_5_10
90_5_11
90_5_12
90_5_13
90_5_14
90_5_15
90_6_1
90_6_2
90_6_3
90_6_4
90_6_5
90_6_6
90_6_7
90_6_8
9

96_10_8
96_10_9
96_10_10
96_10_11
96_10_12
96_10_13
96_10_14
96_10_15
97_1_1
97_1_2
97_1_3
97_1_4
97_1_5
97_1_6
97_1_7
97_1_8
97_1_9
97_1_10
97_1_11
97_1_12
97_1_13
97_1_14
97_1_15
97_2_1
97_2_2
97_2_3
97_2_4
97_2_5
97_2_6
97_2_7
97_2_8
97_2_9
97_2_10
97_2_11
97_2_12
97_2_13
97_2_14
97_2_15
97_3_1
97_3_2
97_3_3
97_3_4
97_3_5
97_3_6
97_3_7
97_3_8
97_3_9
97_3_10
97_3_11
97_3_12
97_3_13
97_3_14
97_3_15
97_4_1
97_4_2
97_4_3
97_4_4
97_4_5
97_4_6
97_4_7
97_4_8
97_4_9
97_4_10
97_4_11
97_4_12
97_4_13
97_4_14
97_4_15
97_5_1
97_5_2
97_5_3
97_5_4
97_5_5
97_5_6
97_5_7
97_5_8
97_5_9
97_5_10
97_5_11
97_5_12
97_5_13
97_5_14
97_5_15
97_6_1
97_6_2
97_6_3
97_6_4
97_6_5
97_6_6
97_6_7
97_6_8
97_6_9
97_6_10
97_6_11
97_6_12
97_6_13
97_6_14
97_6_15
97_7_1
97_7_2
97_7_3
97_7_4
97_7_5
97_7_6
97_7_7
97_7_8
97_7_9
97_7_10
97_7_11
97_7_12
97_7_13
97_7_14
97_7_15
97_8_1
97_8_2
97_8_3
97_8_4
97_8_5
97_8_6
97_8_7
97_8_8
97_8_9
97_8_10
97_8_11
97_8_12
97_8_13
97_8_14
97_8_15
97_9_1
97_9_2
97_9_3
97_9_4
97_9_5
97_9_6


In [143]:
def print_data(data):
    for line in data:
        print(line)
        print('----------------')

In [307]:
zero_data = np.load('zeros.npy')
print_data(zero_data)
for i in zero_data[0]:
    print(i)
    print('---')

[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0. 0. 0.]
----------------
[0. 0. 0. ... 0.

0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---


---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
3.0
---
0.0
---
4.0
---
54.0
---
1.0
---
12.0
---
96.0
---
11.0
---
0.0
---
8.0
---
0.0
---
0.0
---
11.0
---
10.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
22.0
---
0.0
---
0.0
---
0.0
---
42.0
---
98.0
---
0.0
---
0.0
---
8.0
---
0.0
---
0.0
---
0.0
---
3.0
---
3.0
---
4.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0

---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
7.0
---
0.0
---
0.0
---
0.0
---
6.0
---
3.0
---
0.0
---
0.0
---
0.0
---
14.0
---
167.0
---
74.0
---
9.0
---
4.0
---
148.0
---
152.0
---
49.0
---
34.0
---
46.0
---
37.0
---
34.0
---
37.0
---
39.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
1.0
---
1.0
---
0.0
---
0.0
---
6.0
---
0.0
---
0.0
---
19.0
---
64.0
---
165.0
---
69.0
---
19.0
---
0.0
---
10.0
---
0.0
---
112.0
---
197.0
---
131.0
---
146.0
---
149.0
---
164.0
---
184.0
---
177.0
---
63.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
-

---
0.0
---
0.0
---
10.0
---
0.0
---
10.0
---
0.0
---
0.0
---
0.0
---
7.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.0
---
0.